spring:
  datasource:
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:9.6.12://ignored/ignored
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:changelog.xml

graphql:
  spqr:
    gui:
      enabled: true
    relay:
      connection-check-relaxed: true

server:
  port: 8084
